# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 19:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databiable',
            name='cli_nit',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='databiable',
            name='cli_raz_social',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='databiable',
            name='costo',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='databiable',
            name='descuentos_netos',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='databiable',
            name='documento_fc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='databiable',
            name='fecha_generacion_biable',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='databiable',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='databiable',
            name='impuestos_netos',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='databiable',
            name='item_descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='databiable',
            name='item_id',
            field=models.PositiveIntegerField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='databiable',
            name='nro_documento_relacionado',
            field=models.PositiveIntegerField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='databiable',
            name='nro_rm_relacionado',
            field=models.PositiveIntegerField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='databiable',
            name='proyecto_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='databiable',
            name='rentabilidad',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='databiable',
            name='tipo_doc_descripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='databiable',
            name='tipo_documento_relacionado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='databiable',
            name='tipo_rm_relacionado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='databiable',
            name='valor_bruto',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='databiable',
            name='valor_neto',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='databiable',
            name='tipo_docu_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='databiable',
            name='vende_id',
            field=models.PositiveIntegerField(blank=True, max_length=5, null=True),
        ),
    ]
