# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0002_auto_20160930_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databiable',
            name='item_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='databiable',
            name='nro_documento_relacionado',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='databiable',
            name='nro_rm_relacionado',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
