# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0004_auto_20160930_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='databiable',
            name='numero_registros',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
