# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0005_databiable_numero_registros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databiable',
            name='costo',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='databiable',
            name='descuentos_netos',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='databiable',
            name='impuestos_netos',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='databiable',
            name='rentabilidad',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='databiable',
            name='valor_bruto',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='databiable',
            name='valor_neto',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
