# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('nomenclatura', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías Productos',
                'verbose_name': 'Categoría Producto',
            },
        ),
        migrations.CreateModel(
            name='ProductoNombreConfiguracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_categoría_uno', models.BooleanField(default=False)),
                ('con_categoría_dos', models.BooleanField(default=False)),
                ('con_serie', models.BooleanField(default=False)),
                ('con_fabricante', models.BooleanField(default=False)),
                ('con_tipo', models.BooleanField(default=False)),
                ('con_material', models.BooleanField(default=False)),
                ('con_color', models.BooleanField(default=False)),
                ('con_ancho', models.BooleanField(default=False)),
                ('con_alto', models.BooleanField(default=False)),
                ('con_longitud', models.BooleanField(default=False)),
                ('con_diametro', models.BooleanField(default=False)),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mi_configuracion_producto_nombre_estandar', to='productos_categorias.CategoriaProducto', verbose_name='categoría')),
            ],
            options={
                'verbose_name_plural': 'Configuración Nombre Automático',
            },
        ),
    ]
