# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos_categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriados',
            options={'verbose_name': '1.2 Categoría 2', 'verbose_name_plural': '1.2 Categorías 2'},
        ),
        migrations.AlterModelOptions(
            name='categoriaproducto',
            options={'verbose_name': '1.3 Categoría 1', 'verbose_name_plural': '1.3 Categorías 1'},
        ),
        migrations.AlterModelOptions(
            name='tipoproducto',
            options={'verbose_name': '1.1 Tipos Productos', 'verbose_name_plural': '1.1 Tipo Producto'},
        ),
    ]
