branch-defaults:
  default:
    environment: odeco-env
    group_suffix: null
  master:
    environment: odeco-env
global:
  application_name: OdecoPack
  default_ec2_keyname: odecossh
  default_platform: Python 3.4
  default_region: us-west-2
  profile: eb-cli
  sc: git
