# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20160911_1715'),
        ('listasprecios', '0002_auto_20160920_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormasPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(max_length=100)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.Canal')),
            ],
            options={
                'verbose_name_plural': 'Formas de Pago',
            },
        ),
        migrations.AlterUniqueTogether(
            name='diaspago',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='diaspago',
            name='canal',
        ),
        migrations.DeleteModel(
            name='DiasPago',
        ),
        migrations.AlterUniqueTogether(
            name='formaspago',
            unique_together=set([('canal', 'forma')]),
        ),
    ]
