# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listasprecios', '0003_auto_20160920_1719'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormasPago',
            new_name='FormaPago',
        ),
        migrations.RemoveField(
            model_name='variablelistaprecio',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='variablelistaprecio',
            name='referencia',
        ),
        migrations.AddField(
            model_name='variablelistaprecio',
            name='forma_pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listasprecios.FormaPago'),
            preserve_default=False,
        ),
    ]
