# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listasprecios', '0004_auto_20160920_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variablelistaprecio',
            name='forma_pago',
        ),
        migrations.DeleteModel(
            name='VariableListaPrecio',
        ),
    ]
