# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listasprecios', '0005_auto_20160920_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableListaPrecio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listasprecios.FormaPago')),
            ],
            options={
                'verbose_name_plural': 'Variables Lista Precios',
            },
        ),
    ]
