# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0001_initial'),
        ('listasprecios', '0008_auto_20160920_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableBasica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=3, max_digits=10)),
                ('moneda_origen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='importaciones.Moneda')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='variablelistaprecio',
            options={'verbose_name_plural': 'Variables Lista Precios Formas Pago'},
        ),
    ]
