# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listasprecios', '0009_auto_20160920_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variablebasica',
            old_name='valor',
            new_name='factor_importacion',
        ),
        migrations.AddField(
            model_name='variablebasica',
            name='margen_deseado',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
