# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listasprecios', '0011_auto_20160922_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaprecio',
            name='en_lista_precios',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listaprecio',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_lista_precios', to='productos.Producto'),
        ),
    ]
