# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listasprecios', '0013_remove_listaprecio_en_lista_precios'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMargen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='listaprecio',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='listaprecio',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='listaprecio',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='variablebasica',
            name='moneda_origen',
        ),
        migrations.DeleteModel(
            name='ListaPrecio',
        ),
        migrations.DeleteModel(
            name='VariableBasica',
        ),
    ]
