# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listasprecios', '0014_auto_20161010_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablelistaprecio',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=18),
        ),
    ]
