# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listasprecios', '0016_auto_20161011_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variablelistaprecio',
            name='forma_pago',
        ),
        migrations.AlterModelOptions(
            name='categoriamargen',
            options={'verbose_name_plural': '2. Margenes x Categoría'},
        ),
        migrations.DeleteModel(
            name='VariableListaPrecio',
        ),
    ]
