# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listasprecios', '0017_auto_20161011_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriamargen',
            options={'verbose_name_plural': '2. Categorias de Margen'},
        ),
    ]
