# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 16:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(max_length=120)),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
                ('esta_finalizada', models.BooleanField(default=False)),
                ('origen', models.CharField(max_length=120)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tareas',
            },
        ),
    ]
