# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0014_auto_20161014_0953'),
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='origen',
        ),
        migrations.AddField(
            model_name='tarea',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_tareas', to='cotizaciones.Cotizacion'),
        ),
    ]
