# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='cambio',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
            preserve_default=False,
        ),
    ]
