# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorcambiomoneda',
            name='moneda_origen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monedas_origen', to='importaciones.Moneda'),
        ),
        migrations.AlterUniqueTogether(
            name='factorcambiomoneda',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='factorcambiomoneda',
            name='moneda_destino',
        ),
    ]
