# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0002_moneda_cambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneda',
            name='cambio',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
