# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0002_auto_20160920_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorcambiomoneda',
            name='moneda_origen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moneda_cambio', to='importaciones.Moneda'),
        ),
    ]
