# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0003_auto_20160922_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorcambiomoneda',
            name='cambio',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
    ]
