# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0004_auto_20161010_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factorcambiomoneda',
            options={'verbose_name_plural': '2. Tasas de Cambio Monedas'},
        ),
        migrations.AlterModelOptions(
            name='moneda',
            options={'verbose_name_plural': '1. Monedas'},
        ),
    ]
