# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 18:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_auto_20160911_1715'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cliente', to='empresas.Empresa')),
            ],
            options={
                'verbose_name_plural': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='UserExtended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('I', 'Colaborador'), ('E', 'Cliente')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vendedor', to='usuarios.UserExtended')),
            ],
            options={
                'verbose_name_plural': 'vendedores',
            },
        ),
        migrations.AddField(
            model_name='clienteempresa',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cliente_empresa', to='usuarios.UserExtended'),
        ),
    ]
