# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 23:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=1)),
                ('tipo', models.CharField(choices=[('I', 'Interno'), ('E', 'Empresa')], max_length=1)),
                ('avatar', models.ImageField(blank=True, upload_to=usuarios.models.avatar_upload_to)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='clienteempresa',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to='usuarios.UserExtended'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vendedores', to='usuarios.UserExtended'),
        ),
    ]
