# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 18:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_extendido', to=settings.AUTH_USER_MODEL),
        ),
    ]
