# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20160930_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contacto', models.CharField(max_length=12)),
                ('extencion', models.CharField(max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='colaborador', to='usuarios.UserExtended')),
            ],
            options={
                'verbose_name_plural': 'colaboradores',
            },
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
    ]
