# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20161003_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=usuarios.models.colaborador_upload_to, validators=[usuarios.models.Colaborador.validate_image]),
        ),
    ]
