# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_userextended_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteempresa',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cliente_empresa', to='usuarios.UserExtended'),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='tipo',
            field=models.CharField(choices=[('I', 'Colaborador'), ('E', 'Cliente')], max_length=1),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vendedor', to='usuarios.UserExtended'),
        ),
    ]
