# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id_cguno', models.PositiveIntegerField()),
                ('referencia', models.CharField(max_length=120, unique=True)),
                ('descripcion_estandar', models.CharField(max_length=200)),
                ('descripcion_comercial', models.CharField(max_length=200)),
                ('fabricante', models.CharField(blank=True, max_length=60, null=True)),
                ('cantidad_empaque', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.UnidadMedida'),
        ),
    ]
