# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoNombreConfiguracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_categoría_uno', models.BooleanField(default=True)),
                ('con_categoría_dos', models.BooleanField(default=True)),
                ('con_serie', models.BooleanField(default=True)),
                ('con_fabricante', models.BooleanField(default=False)),
                ('con_tipo', models.BooleanField(default=True)),
                ('con_material', models.BooleanField(default=True)),
                ('con_color', models.BooleanField(default=True)),
                ('con_ancho', models.BooleanField(default=False)),
                ('con_alto', models.BooleanField(default=False)),
                ('con_longitud', models.BooleanField(default=False)),
                ('con_diametro', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Configuración Nombre Automático',
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'verbose_name_plural': 'Unidades de Medida'},
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='nomenclatura',
            field=models.CharField(default=1, max_length=3, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colorproducto',
            name='nomenclatura',
            field=models.CharField(default=1, max_length=2, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fabricanteproducto',
            name='nomenclatura',
            field=models.CharField(default=1, max_length=2, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialproducto',
            name='nomenclatura',
            field=models.CharField(default=1, max_length=2, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='con_nombre_automatico',
            field=models.BooleanField(default=False, verbose_name='nombre automático'),
        ),
        migrations.AddField(
            model_name='serieproducto',
            name='nomenclatura',
            field=models.CharField(default=1, max_length=6, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='nomenclatura',
            field=models.CharField(default=1, max_length=2, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='alto',
            field=models.CharField(default='N.A', max_length=120, verbose_name='alto (mm)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ancho',
            field=models.CharField(default='N.A', max_length=120, verbose_name='ancho (mm)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='mis_productos', to='productos.ColorProducto', verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='diametro',
            field=models.CharField(default='N.A', max_length=120, verbose_name='longitud (mm)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='longitud',
            field=models.CharField(default='N.A', max_length=120, verbose_name='longitud (mt)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='mis_productos', to='productos.MaterialProducto', verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='serie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='mis_productos', to='productos.SerieProducto', verbose_name='serie'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(default='N.A', max_length=120, verbose_name='tipo'),
        ),
        migrations.AddField(
            model_name='productonombreconfiguracion',
            name='categoria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mi_configuracion_producto_nombre_estandar', to='productos.CategoriaProducto', verbose_name='categoría'),
        ),
    ]
