# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='activo_catalogo',
            field=models.BooleanField(default=False, verbose_name='En Cata.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='activo_componentes',
            field=models.BooleanField(default=False, verbose_name='En Compo.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='activo_proyectos',
            field=models.BooleanField(default=False, verbose_name='En Proy.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='diametro',
            field=models.CharField(default='N.A', max_length=120, verbose_name='diametro (mm)'),
        ),
    ]
