# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'verbose_name_plural': 'unidades de medida'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='referencia',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='nombre',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
