# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos_categorias', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria_dos',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria_dos_por_categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='mis_productos', to='productos_categorias.CategoriaDosCategoria', verbose_name='categoría dos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_por_categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='mis_productos', to='productos_categorias.TipoProductoCategoría', verbose_name='tipo'),
        ),
    ]
