# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20161020_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_productos', to='productos_caracteristicas.ColorProducto', verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_productos', to='productos_caracteristicas.FabricanteProducto', verbose_name='fabricante'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_productos', to='productos_caracteristicas.MaterialProducto', verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_productos', to='productos_caracteristicas.SerieProducto', verbose_name='serie'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='productos_caracteristicas.UnidadMedida'),
        ),
        migrations.DeleteModel(
            name='ColorProducto',
        ),
        migrations.DeleteModel(
            name='FabricanteProducto',
        ),
        migrations.DeleteModel(
            name='MaterialProducto',
        ),
        migrations.DeleteModel(
            name='SerieProducto',
        ),
        migrations.DeleteModel(
            name='UnidadMedida',
        ),
    ]
