# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_habitacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Habitacion',
        ),
    ]
