# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import productos.models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20160922_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=productos.models.productos_upload_to, validators=[productos.models.Producto.validate_image]),
        ),
    ]
