# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_producto_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo_catalogo',
            field=models.BooleanField(default=True),
        ),
    ]
