# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_auto_20161010_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamargen',
            name='nombre',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
