# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_auto_20161010_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fabricante',
        ),
    ]
