# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0013_auto_20161010_1104'),
        ('productos', '0013_remove_producto_fabricante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria_margen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listasprecios.CategoriaMargen'),
        ),
        migrations.DeleteModel(
            name='CategoriaMargen',
        ),
    ]
