# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_producto_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria_margen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_productos', to='listasprecios.CategoriaMargen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_productos', to='proveedores.Proveedor'),
        ),
    ]
