# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_auto_20161010_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria_margen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
    ]
