# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0019_producto_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_base',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='margen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_con_margen', to='proveedores.MargenProvedor'),
        ),
    ]
