# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0022_auto_20161010_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_empaque',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad_minima_venta',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo_base',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=18),
        ),
    ]
