# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0024_auto_20161010_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='costo_cop',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_base',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
