# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0025_auto_20161010_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='serie',
        ),
        migrations.AddField(
            model_name='producto',
            name='fabricante',
            field=models.CharField(default='', max_length=120),
        ),
    ]
