# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0026_auto_20161011_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='rentabilidad',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
