# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='serie',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
