# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0002_banda_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorcaracteristica',
            name='nombre',
            field=models.CharField(default='HOLA', max_length=60),
            preserve_default=False,
        ),
    ]
