# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0003_valorcaracteristica_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorcaracteristica',
            name='caracteristica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bandas.Caracteristica'),
            preserve_default=False,
        ),
    ]
