# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0007_auto_20161006_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='empujador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='con_empujador', to='bandas.ValorCaracteristica'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='con_serie', to='bandas.ValorCaracteristica'),
        ),
    ]
