# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0008_auto_20161006_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='ancho',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='banda',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bandas_con_color', to='bandas.ValorCaracteristica'),
        ),
        migrations.AddField(
            model_name='banda',
            name='longitud',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='banda',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bandas_con_material', to='bandas.ValorCaracteristica'),
        ),
        migrations.AddField(
            model_name='banda',
            name='varilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bandas_con_varilla', to='bandas.ValorCaracteristica'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='empujador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bandas_con_empujador', to='bandas.ValorCaracteristica'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bandas_con_serie', to='bandas.ValorCaracteristica'),
        ),
    ]
