# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0010_auto_20161007_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bandas_con_color', to='bandas.ValorCaracteristica'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bandas_con_material', to='bandas.ValorCaracteristica'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bandas_con_serie', to='bandas.ValorCaracteristica'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bandas_con_tipo', to='bandas.ValorCaracteristica'),
        ),
    ]
