# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0012_auto_20161007_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='fabricante',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
