# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0013_auto_20161007_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensamblado',
            name='ancho',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='Ancho (mm)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ensamblado',
            name='cortado_a',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banda',
            name='empujador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bandas_con_empujador', to='bandas.ValorCaracteristica'),
            preserve_default=False,
        ),
    ]
