# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0014_auto_20161007_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensamblado',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
