# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0015_auto_20161007_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='empujador_altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Altura'),
        ),
        migrations.AddField(
            model_name='banda',
            name='empujador_ancho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ancho'),
        ),
        migrations.AddField(
            model_name='banda',
            name='empujador_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bandas_con_tipo_empujador', to='bandas.ValorCaracteristica', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='ensamblado',
            name='ancho',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ancho (mm)'),
        ),
    ]
