# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0016_auto_20161007_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='aleta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Aleta (mm)'),
        ),
        migrations.AddField(
            model_name='banda',
            name='aleta_identacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Identacion (mm)'),
        ),
        migrations.AddField(
            model_name='banda',
            name='empujador_distanciado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Distanciado'),
        ),
        migrations.AddField(
            model_name='banda',
            name='empujador_filas_entre',
            field=models.PositiveIntegerField(default=1, verbose_name='Filas entre Empujador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banda',
            name='empujador_identacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Identacion (mm)'),
        ),
        migrations.AddField(
            model_name='banda',
            name='empujador_total_filas',
            field=models.PositiveIntegerField(default=1, verbose_name='Total Filas Empujador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banda',
            name='empujador_altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Altura (mm)'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='empujador_ancho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ancho (mm)'),
        ),
    ]
