# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0017_auto_20161007_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='empujador_filas_entre',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Filas entre Empujador'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='empujador_total_filas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Filas Empujador'),
        ),
    ]
