# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0018_auto_20161007_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='aleta_identacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Identacion Aleta (mm)'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='empujador_distanciado',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Distanciado'),
        ),
    ]
