# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0020_valorcaracteristica_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='referencia',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
