# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0024_ensamblado_precio_linea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensamblado',
            name='precio_linea',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
