# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0025_auto_20161010_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='precio_total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
