# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0026_banda_precio_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
