# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0027_banda_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='aleta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Aleta (mm)'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='aleta_identacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Identacion Aleta (mm)'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='empujador_altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Altura (mm)'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='empujador_ancho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Ancho (mm)'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='empujador_identacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Identacion (mm)'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='precio_total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='ensamblado',
            name='ancho',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Ancho (mm)'),
        ),
        migrations.AlterField(
            model_name='ensamblado',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='ensamblado',
            name='precio_linea',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
