# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0029_auto_20161011_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='costo_base_total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='ensamblado',
            name='costo_cop_linea',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
