# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0030_auto_20161011_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='rentabilidad',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='ensamblado',
            name='rentabilidad',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
