# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0031_auto_20161011_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoEnsambladoBlanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='banda',
            name='aleta',
        ),
        migrations.AddField(
            model_name='banda',
            name='aleta_altura',
            field=models.PositiveIntegerField(default=0, verbose_name='Altura (mm)'),
        ),
        migrations.AddField(
            model_name='banda',
            name='id_cguno',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banda',
            name='paso',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='banda',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='aleta_identacion',
            field=models.CharField(default='N.A', max_length=10, verbose_name='Identacion'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='ancho',
            field=models.PositiveIntegerField(default=0, verbose_name='Ancho (mm)'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='empujador_altura',
            field=models.PositiveIntegerField(default=0, verbose_name='Altura (mm)'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='empujador_ancho',
            field=models.PositiveIntegerField(default=0, verbose_name='Ancho (mm)'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='empujador_distanciado',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Distanciado (mm)'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='empujador_identacion',
            field=models.CharField(default='N.A', max_length=10, verbose_name='Identacion'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='fabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandas_con_fabricante', to='bandas.ValorCaracteristica'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='longitud',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Longitud (m)'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='total_filas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ensamblado',
            name='ancho',
            field=models.PositiveIntegerField(default=0, verbose_name='Ancho (mm)'),
        ),
        migrations.AlterField(
            model_name='ensamblado',
            name='cantidad',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='ensamblado',
            name='cortado_a',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
