# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0032_auto_20161012_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banda',
            old_name='fabricante',
            new_name='uno',
        ),
    ]
