# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0035_banda_fabricante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='empujador_distanciado',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Distanciado (mm)'),
        ),
    ]
