# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0036_auto_20161012_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='costoensambladoblanda',
            name='aleta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='costoensambladoblanda',
            name='empujador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='costoensambladoblanda',
            unique_together=set([('aleta', 'empujador')]),
        ),
    ]
