# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0038_auto_20161012_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorcaracteristica',
            name='nomenclatura',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='valorcaracteristica',
            unique_together=set([('caracteristica', 'nombre'), ('caracteristica', 'nomenclatura')]),
        ),
    ]
