# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0039_auto_20161012_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banda',
            options={'permissions': (('full_bandas', 'Full Bandas'),)},
        ),
    ]
