# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0040_auto_20161013_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='costo_mano_obra',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
