# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0041_banda_costo_mano_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='precio_banda',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
