# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 22:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0006_auto_20160922_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('INI', 'Iniciado'), ('ENV', 'Enviada')], default='INI', max_length=10)),
                ('nro_contacto', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('nombres_contacto', models.CharField(blank=True, max_length=120)),
                ('apellidos_contacto', models.CharField(blank=True, max_length=120)),
                ('razon_social', models.CharField(blank=True, max_length=120)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=0, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cotizaciones.Cotizacion')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='productos.Producto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
