# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_auto_20160928_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='ciudad',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='pais',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
