# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listasprecios', '0011_auto_20160922_1100'),
        ('cotizaciones', '0004_auto_20161003_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcotizacion',
            name='forma_pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items_cotizaciones', to='listasprecios.FormaPago'),
            preserve_default=False,
        ),
    ]
