# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0005_itemcotizacion_forma_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcotizacion',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
