# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0006_auto_20161003_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='nro_cotizacion',
            field=models.CharField(default='HOLA', max_length=120),
            preserve_default=False,
        ),
    ]
