# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0007_cotizacion_nro_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_envio',
            field=models.DateField(null=True),
        ),
    ]
