# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0029_auto_20161011_1413'),
        ('cotizaciones', '0010_auto_20161010_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcotizacion',
            name='banda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='bandas.Banda'),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='productos.Producto'),
        ),
    ]
