# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0011_auto_20161011_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'permissions': (('full_cotizacion', 'Full Cotizacion'),)},
        ),
    ]
