# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0012_auto_20161013_1642'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cotizacion',
            managers=[
                ('estados', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='dias_entrega',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
