# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0015_remisioncotizacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remisioncotizacion',
            options={'verbose_name_plural': 'Remisiones x Cotización'},
        ),
        migrations.AddField(
            model_name='remisioncotizacion',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remisioncotizacion',
            name='fecha_prometida_entrega',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remisioncotizacion',
            name='nro_factura',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remisioncotizacion',
            name='nro_remision',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
