# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0016_auto_20161014_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='remisioncotizacion',
            name='cotizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.Cotizacion'),
            preserve_default=False,
        ),
    ]
