# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0017_remisioncotizacion_cotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaCotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(max_length=120)),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
                ('esta_finalizada', models.BooleanField(default=False)),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_tareas', to='cotizaciones.Cotizacion')),
            ],
            options={
                'verbose_name_plural': 'Tareas',
            },
        ),
        migrations.AlterField(
            model_name='remisioncotizacion',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_remisiones', to='cotizaciones.Cotizacion'),
        ),
    ]
