# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0019_auto_20161018_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('INI', 'Iniciado'), ('ENV', 'Enviada'), ('ELI', 'Rechazada'), ('REC', 'Recibida'), ('PRO', 'En Proceso'), ('FIN', 'Entragada Totalmente')], default='INI', max_length=10),
        ),
    ]
