# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_delete_habitacion'),
        ('proveedores', '0002_auto_20160911_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listaprecio',
            options={'verbose_name_plural': 'listas de precios'},
        ),
        migrations.AlterUniqueTogether(
            name='listaprecio',
            unique_together=set([('proveedor', 'producto', 'cantidad_minima')]),
        ),
    ]
