# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_auto_20160911_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableListaPrecio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Variables Lista Precios',
            },
        ),
    ]
