# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_variablelistaprecio_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablelistaprecio',
            name='referencia',
            field=models.CharField(max_length=15),
        ),
    ]
