# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0007_auto_20160914_1439'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listaprecio',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='listaprecio',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='listaprecio',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='VariableListaPrecio',
        ),
        migrations.DeleteModel(
            name='ListaPrecio',
        ),
    ]
