# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0009_auto_20160920_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='factor_importacion',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
    ]
