# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_remove_producto_fabricante'),
        ('proveedores', '0011_auto_20161010_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='margenprovedor',
            options={'verbose_name_plural': 'proveedores'},
        ),
        migrations.AlterField(
            model_name='margenprovedor',
            name='margen_deseado',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Margen (%)'),
        ),
        migrations.AlterUniqueTogether(
            name='margenprovedor',
            unique_together={('categoria', 'proveedor')},
        ),
    ]
