# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0014_auto_20161010_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='margenprovedor',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margenes_categoria', to='listasprecios.CategoriaMargen'),
        ),
        migrations.AlterField(
            model_name='margenprovedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margenes_por_proveedor', to='proveedores.Proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provedores_con_moneda', to='importaciones.Moneda'),
        ),
    ]
