# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0016_auto_20161010_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='margenprovedor',
            name='margen_deseado',
            field=models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Margen (%)'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='factor_importacion',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=18),
        ),
    ]
