# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0018_auto_20161011_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='margenprovedor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='margenprovedor',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
