# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0019_auto_20161013_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='margenprovedor',
            options={'verbose_name_plural': '2. Margenes x Categoría x Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': '1. Proveedores'},
        ),
    ]
